runtime: php55
api_version: 1

handlers:
- url: /WinRate.php
  script: WinRate.php

- url: /BanRate.php
  script: BanRate.php

- url: /PickRate.php
  script: PickRate.php

- url: /
  script: WinRate.php